x-default: &default
  build: .
  volumes:
    - ".:/app"
    - "./opt:/app/opt"
    - "${CHARSPEAK_STORAGE_DIR}/assets:/app/assets"
    - "${CHARSPEAK_STORAGE_DIR}:/storage"
  shm_size: "12gb"
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: [ '0' ]
            capabilities: [ gpu ]

services:
  api:
    <<: *default
    hostname: rvc_api
    command: uvicorn server.main:app --host 0.0.0.0 --port 7866
    ports:
      - "${RVC_PORT}:7866"
    environment:
      RVC_PORT: 7866

  webui:
    <<: *default
    ports:
      - "${RVC_WEBUI_PORT}:7865"
    environment:
      RVC_PORT: 7865

networks:
  default:
    name: charspeak
    external: true